server:
  port: 8080
spring:
  cloud:
    consul:
      discovery:
        instanceId: gatway
        health:
          check:
            interval: 5s
spring:
  cloud:
    gateway:
      routes:
      - id: service-b
        uri: lb://service-b
        predicates:
        - Cookie=mycookie,mycookievalue
        - Path=/srvb/**